name             'sysinternals'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs Microsoft SysInternals tools'
version          '1.1.7'
supports 'windows'
source_url       'https://github.com/sous-chefs/sysinternals'
issues_url       'https://github.com/sous-chefs/sysinternals/issues'
chef_version     '>= 15.3'
