name             'sysinternals'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'Installs Microsoft SysInternals tools'
version          '1.1.1'
supports 'windows'
source_url       'https://github.com/chef-cookbooks/sysinternals'
issues_url       'https://github.com/chef-cookbooks/sysinternals/issues'
chef_version     '>= 12.6'
